filter_step:
  HESIN_DATA_PATH: data/data_hesin/data_hesin.csv
  CODES_PATH: data/pipelines/z-score-pipeline/wanted_diseases.yaml
  method: keep # can also be "drop"
  FILTER_PATH: data/information_data/eid_age_sex.csv
  OUTPUT_PATH: data/pipelines/z-score-pipeline/
  filteration:
    Age at recruitment:
      young: { min: 40, max: 55 }
      old: { min: 56, max: 69 }

#filter_step:
#  HESIN_DATA_PATH: data/data_hesin/data_hesin.csv
#  CODES_PATH: data/pipelines/z-score-pipeline/wanted_diseases.yaml
#  method: keep # can also be "drop"
#  FILTER_PATH: data/information_data/eid_age_sex.csv
#  OUTPUT_PATH: data/pipelines/z-score-pipeline/
#  filteration: None