filter_step:
  experiment_name: exp1
  HESIN_DATA_PATH: data/data_hesin/data_hesin.csv
  CODES_PATH: data/pipelines/z_score_pipeline/codes_files/wanted_diseases.yaml
  method: keep # can also be "drop"
  FILTER_PATH: data/information_data/eid_age_sex.csv
  OUTPUT_PATH: data/pipelines/z_score_pipeline/
  filteration:
    Age at recruitment:
      young: { min: 40, max: 55 }
      old: { min: 56, max: 69 }