# Global experiment configuration
experiment_name: poc

filter_step:
  HESIN_DATA_PATH: data/data_hesin/data_hesin.csv
  CODES_PATH: data/pipelines/z_score_pipeline/codes_files/poc.yaml
  method: keep # can also be "drop"
  FILTER_PATH: data/information_data/eid_age_sex.csv
  OUTPUT_PATH: data/pipelines/z_score_pipeline/
  filteration:
    Age at recruitment:
      young: { min: 40, max: 55 }
      old: { min: 56, max: 69 }

bootstrap_step:
  OUTPUT_BASE_DIR: data/pipelines/z_score_pipeline/
  FIELDS_TO_KEEP:
    - dnx_hesin_diag_id
    - eid
    - diag_icd10
  SHUFFLE_ITERATIONS: 100
  SAVE_BOOTSTRAP_DATA: false

disease_score_step:
  OUTPUT_BASE_DIR: data/pipelines/z_score_pipeline/

calculate_ci_step:
  OUTPUT_BASE_DIR: data/pipelines/z_score_pipeline/
  Z_ALPHA: 1.96  # Z-score for 95% confidence interval (use 2.576 for 99% CI)

analyze_ci_step:
  OUTPUT_BASE_DIR: data/pipelines/z_score_pipeline/
  UPPER_THRESHOLD: 2.0  # Threshold multiplier for upper CI comparison
  LOWER_THRESHOLD: 10.0  # Threshold multiplier for lower CI comparison

